---
name: Rust - Check formatting
on:
  pull_request:
    paths:
      - .github/workflows/rustfmt.yml
      - rustfmt.toml
      - '**/*.rs'
  workflow_dispatch:
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
          default: true

      - name: Check formatting
        run: |-
          rustfmt --version
          cargo fmt -- --check
